CREATE TABLE ORDERS (
  ORDER_ID      VARCHAR2(20) NOT NULL,
  ORDER_DATE    DATE NOT NULL,
  DELIVERY_DATE DATE,
  QTY           NUMBER(9)
);
COMMENT ON COLUMN ORDERS.DELIVERY_DATE IS 'Delivery date';

CREATE OR REPLACE PACKAGE BODY ORDER_PKG AS

  PROCEDURE INSERT_ORDER(p_id IN VARCHAR2, p_date IN DATE, p_delivery IN DATE) IS
  BEGIN
    IF p_delivery < p_date THEN
      RAISE_APPLICATION_ERROR(-20001, 'delivery before order');
    END IF;
    INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, DELIVERY_DATE) VALUES (p_id, p_date, p_delivery);
  END INSERT_ORDER;

  FUNCTION COUNT_ORDERS RETURN NUMBER IS
    n NUMBER;
  BEGIN
    SELECT COUNT(*) INTO n FROM ORDERS;
    RETURN n;
  END COUNT_ORDERS;

END ORDER_PKG;
/

CREATE OR REPLACE PACKAGE BODY AUDIT_PKG AS
  PROCEDURE LOG_IT(p_msg IN VARCHAR2);

  PROCEDURE RUN IS
  BEGIN
    LOG_IT('run');
  END RUN;

  PROCEDURE LOG_IT(p_msg IN VARCHAR2) IS
  BEGIN
    NULL;
  END LOG_IT;
END AUDIT_PKG;
/
